# Generated by Django 5.0.6 on 2024-05-29 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="금기정보",
            fields=[
                ("금기코드", models.IntegerField(primary_key=True, serialize=False)),
                ("금기유형", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="제품",
            fields=[
                ("제품코드", models.IntegerField(primary_key=True, serialize=False)),
                ("품목기준코드", models.IntegerField(null=True)),
                ("제품명", models.TextField()),
                ("주성분코드", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="업체",
            fields=[
                ("업체코드", models.IntegerField(primary_key=True, serialize=False)),
                ("업체명", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="품목_사용정보",
            fields=[
                ("품목기준코드", models.IntegerField(primary_key=True, serialize=False)),
                ("효능", models.TextField(null=True)),
                ("사용법", models.TextField(null=True)),
                ("주의사항경고", models.TextField(null=True)),
                ("주의사항", models.TextField(null=True)),
                ("상호작용", models.TextField(null=True)),
                ("부작용", models.TextField(null=True)),
                ("보관법", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="노인주의상세정보",
            fields=[
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="medicine.제품",
                    ),
                ),
                ("노인주의_약품상세정보", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="연령별금기상세정보",
            fields=[
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="medicine.제품",
                    ),
                ),
                ("특정연령", models.IntegerField()),
                ("특정연령단위", models.TextField()),
                ("연령처리조건", models.TextField()),
                ("상세정보", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="용량주의상세정보",
            fields=[
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="medicine.제품",
                    ),
                ),
                ("일일최대투여량", models.TextField()),
                ("일일최대투여기준량", models.FloatField()),
                ("용량주의_상세내용", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="임부금기상세정보",
            fields=[
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="medicine.제품",
                    ),
                ),
                ("임부금기_금기등급", models.TextField()),
                ("임부금기_상세정보", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="제품_상세정보",
            fields=[
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="medicine.제품",
                    ),
                ),
                ("ATC코드", models.TextField(null=True)),
                ("규격", models.TextField()),
                ("단위", models.TextField()),
                ("상한금액", models.TextField(null=True)),
                ("전일", models.TextField()),
                ("급여여부", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="투여기간상세정보",
            fields=[
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="medicine.제품",
                    ),
                ),
                ("최대투여기간일수", models.IntegerField()),
                ("주성분함량", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="효능군중복상세정보",
            fields=[
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="medicine.제품",
                    ),
                ),
                ("효능군중복_효능군", models.TextField()),
                ("효능군중복_Group", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="성분",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("주성분코드", models.CharField(max_length=255)),
                ("성분명", models.CharField(max_length=255)),
                ("제형", models.TextField(null=True)),
            ],
            options={
                "unique_together": {("주성분코드", "성분명")},
            },
        ),
        migrations.AddField(
            model_name="제품",
            name="업체코드",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="medicine.업체"
            ),
        ),
        migrations.CreateModel(
            name="병용금기상세정보",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("상대제품코드", models.IntegerField()),
                ("상세정보", models.TextField()),
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medicine.제품"
                    ),
                ),
            ],
            options={
                "unique_together": {("제품코드", "상대제품코드")},
            },
        ),
        migrations.CreateModel(
            name="제품_금기정보",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "금기코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medicine.금기정보"
                    ),
                ),
                (
                    "제품코드",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medicine.제품"
                    ),
                ),
            ],
            options={
                "unique_together": {("제품코드", "금기코드")},
            },
        ),
    ]
